---
- name: disable guest account
  become: true
  ini_file: 
    path: /usr/share/lightdm/lightdm.conf.d/50-ubuntu.conf
    section: "Seat:*"
    option: "allow-guest"
    value: "false"
  notify: restart lightdm 
  register: disable_guest_account
