- import_tasks: release_notes.yml 
  tags: customizations_release_notes
  when: release_notes is defined and release_notes
- import_tasks: shared_folder.yml 
  tags: customizations_shared_folder
- import_tasks: global_bashrc.yml 
  tags: customizations_global_bashrc
- import_tasks: folders.yml 
  tags: customizations_folders

- name: lightdm-related
  block:
    - import_tasks: disable_guestuser.yml 
      tags: customizations_disable_guestuser
    - import_tasks: wallpaper.yml 
      tags: customizations_wallpaper
    - import_tasks: launcher.yml 
      tags: customizations_launcher
    - import_tasks: disable_autolock.yml 
      tags: customizations_disable_autolock
    - import_tasks: autologin.yml 
      tags: customizations_autologin
    - import_tasks: chromium_keyring.yml 
      tags: customizations_chromium_keyring
    - meta: flush_handlers
  when: not customizations_headless
