- hosts: default
  name: playbook for the {{ globalconfig.vm_name }}
  pre_tasks:
    - name: import global variables
      include_vars:
        file: globalconfig.yml
        name: globalconfig
  roles: 
    - common
    - customizations
    - editors
    - scheduler
    - simulationtools
  vars:
    - hostname: marvelvm


