- name: playbook for the MARVEL VM
  hosts: default
  pre_tasks:
    - name: import global variables
      include_vars:
        file: globalconfig.yml
        name: globalconfig
  roles: 
    - role: common
      tags: common
    - role: customizations
      tags: customizations
    - role: editors
      tags: customizations
    - role: scheduler
      tags: scheduler
    - role: simulationtools
      tags: simulationtools
