- name: set up the VM
  hosts: vms
  vars:
    - run_tests: True
    - clean: False
  pre_tasks:
    - name: import global variables
      tags: always
      include_vars:
        file: globalconfig.yml
        name: globalconfig
  roles: 
    - role: common
      tags: common
    - role: customizations
      tags: customizations
    - role: editors
      tags: editors
    - role: scheduler
      tags: scheduler
    - role: simulationtools
      tags: simulationtools
    - role: quantum_espresso
      tags: quantum_espresso
    - role: yambo
      tags: yambo
    - role: fleur
      tags: fleur
    - role: siesta
      tags: siesta
    - role: cp2k
      tags: cp2k
    - role: wannier90
      tags: wannier90
    - role: aiida
      tags: aiida
    - role: jupyter
      tags: jupyter
