aiida_version: "0.11.0"
aiida_extras:
  - REST
  - docs
  - atomic_tools
  - testing
  - notebook
aiida_run_folder: "{{ ansible_env.HOME }}/.aiida_run"
aiida_localhost_name: localhost
postgres_pw: "ne9N_LDK-*JSS"
postgres_db: aiidadb
postgres_user: aiida
aiida_venv: "{{ ansible_env.HOME }}/.virtualenvs/aiida"

# plugins
aiida_fleur_version: "0.6.0"
aiida_siesta_version: "0.9.8"
aiida_cp2k_version: "0.7"
aiida_yambo_version: "0.2-beta"

# pseudos
aiida_pseudopotentials:
# Problem: sssp efficiency has 2 pseudos for Be.
# Nicolas Mounet is informed.
#  - name: sssp-pbe-efficiency
#    file: SSSP_eff_PBE.tar.gz
#    url: http://materialscloud.org/sssp/pseudos
#    folder: SSSP_eff_PBE
#    home_page: http://materialscloud.org/sssp/
#    description: >-
#     Standard Solid State Pseudopotentials (efficiency) 
#     for the PBE functional
  - name: sssp-pbe-accuracy
    file: SSSP_acc_PBE.tar.gz
    url: http://materialscloud.org/sssp/pseudos
    folder: SSSP_acc_PBE
    home_page: http://materialscloud.org/sssp/
    description: >-
     Standard Solid State Pseudopotentials (accuracy) 
     for the PBE functional
  - name: sg15-oncv-1.1
    file: sg15_oncv_upf_2015-10-07.tar.gz
    url: http://www.quantum-simulation.org/potentials/sg15_oncv
    folder: sg15-oncv-1.1
    home_page: http://www.quantum-simulation.org/potentials/sg15_oncv/
    description: >-
     SG15 Optimized Norm-Conserving Vanderbilt (ONCV) pseudopotentials
