---
- name: run Wannier90 default tests
  shell: "make run-tests"
  args:
    chdir: "{{ w90_topdir }}/test-suite"
  register: w90_tests

- name: run Wannier90 default tests
  shell: "make clean"
  args:
    chdir: "{{ w90_topdir }}/test-suite"
  when: w90_tests
