---
#- include_tasks: install_via_apt.yml
#- include_tasks: install_via_make.yml
- include_tasks: download_binary.yml

- name: Add cp2k info (version) to Release Notes file
  ini_file:
    path: "{{ release_notes_file }}"
    section: "cp2k"
    option: "version"
    value: "{{ cp2k_version }}"

