---
- name: "install aiida-yambo-{{ aiida_yambo_version }} from PyPI"
  pip:
    name: aiida-yambo
    version: "{{ aiida_yambo_version }}"
    virtualenv: "{{ aiida_venv }}"
  register: pip_install

- name: run reentry scan
  shell: "{{ aiida_venv }}/bin/reentry scan -r aiida"
  when: pip_install.changed

# Do not use the yambo_executables directly because not all of them
# have an AiiDA plugin
- name: set up Yambo codes for localhost
  include_tasks: code-setup.yml code={{ item }} 
  with_items: 
   - yambo
   - p2y
  vars:
   - aiida_code_name:  "{{code}}-{{yambo_version}}"
   - aiida_code_template:  yambo.code
   - aiida_computer_name:  "{{ aiida_localhost_name }}"
  when: yambo_executables is defined

- include_role:
    name: release_notes
  vars:
    section: AiiDA
    option: aiida-yambo
    value: >-
      aiida-yambo {{ aiida_yambo_version }} is installed.
  when: release_notes is defined and release_notes
