- name: set up QE codes for localhost
  include_tasks: code-setup.yml code={{ item }}
  with_items: "{{qe_executables}}"
  vars:
   - aiida_code_name:  "qe-{{code}}-{{qe_version}}"
   - aiida_code_template:  qe.code
   - aiida_computer_name:  "{{ aiida_localhost_name }}"

- name: Add AiiDA info (codes) to Release Notes file
  ini_file:
    path: "{{ release_notes_file }}"
    section: "AiiDA"
    option: "aiida-quantumespresso"
    value: >-
      A number of codes are already installed and preconfigured. 
      See 'verdi code list'
