- name: set up QE codes for localhost
  include_tasks: code-setup.yml code={{ item }}
  with_items: "{{qe_executables}}"
  vars:
   - aiida_code_name:  "qe-{{code}}-{{qe_version}}"
   - aiida_code_template:  qe.code
   - aiida_computer_name:  "{{ aiida_localhost_name }}"
  when: qe_executables is defined

## Not tested yet; to activate when the Yambo plugin becomes public
## (Note that we have to install the aiida-yambo plugin as well)  
#- name: set up Yambo codes for localhost
#  include_tasks: code-setup.yml code={{ item }} 
#  with_items: 
#   - yambo
#   - p2y
#  vars:
#   - aiida_code_name:  "yambo-{{code}}-{{qe_version}}"
#   - aiida_code_template:  yambo.code
#   - aiida_computer_name:  "{{ aiida_localhost_name }}"
#  # I don't use the yambo_executables directly because not all of them
#  # have an AiiDA plugin
#  when: yambo_executables is defined

- name: Add AiiDA info (codes) to Release Notes file
  ini_file:
    path: "{{ release_notes_file }}"
    section: "AiiDA"
    option: "configured codes"
    value: "A number of codes are already installed and preconfigured. You can get the full list using 'verdi code list'"
