---
- name: check if the AiiDA computer is already present
  shell: "{{ aiida_venv }}/bin/verdi computer show {{ aiida_computer_name }}"
  ignore_errors: True
  register: aiida_check_computer
  changed_when: False

- name: Copy the script to setup the {{ aiida_computer_name }} AiiDA computer
  template:
    src: "{{ aiida_computer_name }}.computer"
    dest: "${HOME}/.local/share/marvelnccr/"
    mode: 0755
  when: aiida_check_computer.rc != 0

- name: "Setup {{ aiida_computer_setup }} computer for AiiDA"
  shell: "cat ${HOME}/.local/share/marvelnccr/{{ aiida_computer_name }}.computer | {{ aiida_venv }}/bin/verdi computer setup" 
  when: aiida_check_computer.rc != 0

- name: "Configure localhost"
  shell: "{{ aiida_venv }}/bin/verdi computer configure {{ aiida_computer_name }}" 
  when: (aiida_check_computer.rc != 0) and (aiida_computer_name == aiida_localhost_name)
