---
- name: Setup postgres db
  become: True
  become_user: postgres
  postgresql_db:
    name: "{{ aiida_postgres_db }}"
- name: Setup postgres user
  become: True
  become_user: postgres
  postgresql_user:
    db: "{{ aiida_postgres_db }}"
    name: "{{ aiida_postgres_user }}"
    password: "{{ aiida_postgres_pw }}"
