- name: Create folder for codes
  file:
      path: "{{ globalconfig.vm_codes_folder }}"
      state: directory

- name: Create folder for examples
  file:
      path: "{{ globalconfig.vm_examples_folder }}"
      state: directory


