#- name: Update repositories cache and install "quantum-espresso" package
#  become: true
#  apt:
#      name: quantum-espresso
#      present: false

- name: Install Nagios prerequisites for Debian
  apt: pkg={{ item }} state=present
  become: true
  with_items:
   - linux-headers-{{ ansible_kernel }}
   - build-essential
   - python-passlib

- name: Create folder for codes
  file:
      path: "{{ ansible_env.HOME }}/codes"
      state: directory

# Will only download once  
- name: Get Quantum ESPRESSO
  get_url: url={{ qe_url }} dest={{ ansible_env.HOME }}/codes/{{ qe_src }}.tar.gz

- name: Unpack Quantum ESPRESSO source files
  shell: "cd {{ ansible_env.HOME }}/codes && tar -xzvf {{ qe_src }}.tar.gz"
  args:
    creates: "{{ ansible_env.HOME }}/codes/{{ qe_src }}"

- name: Configure QE
  shell: cd {{ ansible_env.HOME }}/codes/{{ qe_src }} && ./configure --enable-parallel
  args:
    creates: "{{ ansible_env.HOME }}/codes/{{ qe_src }}/make.inc"

- name: Make QE executables
  shell: "cd {{ ansible_env.HOME }}/codes/{{ qe_src }} && make {{ item }}"
  args:
    creates: "{{ ansible_env.HOME }}/codes/{{ qe_src }}/bin/{{ item }}.x"
  with_items:
    - pw
    - cp
    - pp
    - ph

- name: "Put a line in ~/.bashrc to add QE to the path"
  lineinfile: 
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: "export PATH=${PATH}:{{ ansible_env.HOME }}/codes/{{ qe_src }}/bin/"

