---
- name: apt clean
  become: True
  listen:
  - apt clean
  apt:
      autoclean: True

- name: remove ~/.cache
  listen:
  - apt clean
  - clean cache
  file:
    state: absent
    path: "${HOME}/.cache"

- name: apt autoremove
  become: True
  listen:
  - apt clean
  apt:
      autoremove: True
