- name: "VM release notes: Add '{{ option }}' to '{{ section }}'"
  ini_file:
    path: "{{ release_notes_vm }}"
    section: "{{ section }}"
    option: "{{ option }}"
    value: "{{ value }}"
    create: True

- name: "localhost release notes: Add '{{ option }}' to '{{ section }}'"
  delegate_to: localhost
  ini_file:
    path: "{{ release_notes_localhost }}"
    section: "{{ section }}"
    option: "{{ option }}"
    value: "{{ value }}"
    create: True
  when: release_notes is defined and release_notes_locally
