qe_version: "6.2.1"
qe_src_archive: "qe-{{ qe_version }}.tar.gz"
#qe_url: "http://www.qe-forge.org/gf/download/frsrelease/240/1075/{{qe_src_archive }}"
qe_url: "https://github.com/QEF/q-e/archive/{{ qe_src_archive }}"

qe_src: "q-e-qe-{{ qe_version }}"
qe_topdir: "{{ globalconfig.vm_codes_folder }}/{{qe_src}}"
qe_executables:
  - pw
  - cp
  - pp
  - ph
  - neb
