# Will only download once
- name: Get Yambo
  get_url: 
    url: "{{ yambo_url }}"
    dest: "{{ globalconfig.vm_codes_folder }}/{{ yambo_src_archive }}"
  register: yambo_download

- name: Extract yambo source
  unarchive:
    src: "{{ yambo_download.dest }}"
    dest: "{{ globalconfig.vm_codes_folder }}"
    remote_src: True

- name: Configure Yambo
  shell: ./configure
  args:
    chdir: "{{ yambo_topdir }}"
    creates: "{{ yambo_topdir }}/Makefile"

- name: Make Yambo executables
  shell: "make {{ item }}"
  args:
    chdir: "{{ yambo_topdir }}"
    creates: "{{ yambo_topdir }}/bin/{{ item }}"
  with_items: "{{ yambo_executables }}"

- name: "Put a line in ~/.bashrc to add Yambo to the path"
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: "export PATH=${PATH}:{{ yambo_topdir }}/bin/"
    # Do this also non-interactively
    insertbefore: "{{ reference_point_bashrc_string }}"

- name: Add Yambo info (version) to Release Notes file
  ini_file:
    path: "{{ release_notes_file }}"
    section: "Yambo"
    option: "version"
    value: "{{ yambo_version }}"

- name: Add Yambo info (location) to Release Notes file
  ini_file:
    path: "{{ release_notes_file }}"
    section: "Yambo"
    option: "usage"
    value: >-
       Yambo is compiled and installed in {{ yambo_topdir }}.
       Simply run 'yambo'.
