- name: "get the machine hostname"
  become: true
  shell: "hostname"
  register: cur_hostname_command
  changed_when: False

- name: "set the machine hostname"
  become: true
  shell: "hostname {{ hostname }}"
  when: cur_hostname_command.stdout != hostname

- name: "get the hostname from file"
  become: true
  shell: "cat /etc/hostname"
  register: cur_hostnamefile_command
  changed_when: False

- name: "set the hostname in /etc/hostname"
  become: true
  shell: "echo '{{ hostname }}' > /etc/hostname"
  when: cur_hostnamefile_command.stdout != hostname

- name: Create variable from command
  shell: "ip -4 addr show | grep -Po 'inet \\K[\\d.]+' | grep -v 127.0.0.1 | head -n1"
  register: ip_address_command
  changed_when: False

- name: "I first clean up the lines with 127.0.0.1"
  become: true
  lineinfile: 
    path: "/etc/hosts"
    regexp: '^127\.0\.1\.1'
    owner: root
    group: root
    mode: 0644
    state: absent

- name: "set 127.0.1.1 to localhost (if it's set to the hostname, pbs server will complain"
  become: true
  lineinfile: 
    path: "/etc/hosts"
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1 localhost"
    owner: root
    group: root
    mode: 0644

- name: "set the hostname in /etc/hosts"
  become: true
  lineinfile: 
    path: "/etc/hosts"
    regexp: "{{ hostname }}$"
    line: "{{ ip_address_command.stdout }} {{ hostname }}"
    owner: root
    group: root
    mode: 0644
