- include_tasks: debug.yml
- include_tasks: password.yml
- include_tasks: bashrc_refpoint.yml
- include_tasks: swap.yml
- include_tasks: packages.yml
- include_tasks: ubuntu_desktop.yml
  when: not headless
- include_tasks: hostname.yml
- include_tasks: timezone.yml
