- import_tasks: password.yml
  tags: common_password
- import_tasks: bashrc_refpoint.yml
  tags: common_bashrc
- import_tasks: swap.yml
  tags: common_swap
- import_tasks: packages.yml
  tags: common_packages
- import_tasks: ubuntu_desktop.yml
  tags: common_desktop
  when: not common_headless
- import_tasks: hostname.yml
  tags: common_hostname
- import_tasks: timezone.yml
  tags: common_timezone

