- import_tasks: debug.yml
- import_tasks: password.yml
- import_tasks: bashrc_refpoint.yml
- import_tasks: swap.yml
- import_tasks: packages.yml
- import_tasks: ubuntu_desktop.yml
  when: not headless
- import_tasks: hostname.yml
- import_tasks: timezone.yml
