- name: Update repositories cache
  become: true
  apt:
      update_cache: yes

- name: Install further needed packages
  become: true
  apt:
      name: "{{item}}"
      state: latest
  with_items:
      - python-pip
      - python-dev
  notify: apt clean

- name: Install ubuntu-desktop (required packages only)
  become: true
  apt:
      name: ubuntu-desktop
      state: latest
      install_recommends: False
  notify: apt clean

  # important packages missed by 'apt install ubuntu-desktop --no-recommends'
  # (because dependencies also omit their recommended packages)
  # see https://askubuntu.com/questions/964723/is-there-a-non-recursive-no-install-recommends-for-apt-get-install
- name: Add essential recommended packages of dependencies
  become: True
  apt:
      name: "{{ item }}"
      state: latest
  with_items:
  - xserver-xorg-video-vesa
  - xserver-xorg-video-vmware
  - indicator-session

  ## See full list on https://packages.ubuntu.com/xenial/ubuntu-desktop
- name: add some, but not all recommended packages of ubuntu-desktop
  become: True
  apt:
      name: "{{ item }}"
      state: latest
  with_items:
  - acpi-support
  - activity-log-manager
  - app-install-data-partner
  - apport-gtk
  - avahi-autoipd
  - avahi-daemon
  - baobab
  - brltty
  - evince
  - file-roller
  - firefox
  - gedit
  - gnome-accessibility-themes
  - gnome-calculator
  - gnome-disk-utility
  - gnome-font-viewer
  - gnome-keyring
  - gnome-power-manager
  - gnome-screenshot
  - gnome-system-log
  - gnome-system-monitor
  - gnome-terminal
  - gucharmap
  - gvfs-fuse
  - im-config
  - kerneloops-daemon
  - laptop-detect
  - libgail-common
  - libnss-mdns
  - libpam-gnome-keyring
  - libproxy1-plugin-gsettings
  - libproxy1-plugin-networkmanager
  - mousetweaks
  - nautilus-share
  - network-manager-gnome
  - network-manager-pptp-gnome
  - overlay-scrollbar-gtk2
  - pcmciautils
  - plymouth-theme-ubuntu-logo
  - policykit-desktop-privileges
  - ppp
  - pppconfig
  - pppoeconf
  - python3-aptdaemon.pkcompat
  - qt-at-spi
  - snapd
  - sni-qt
  - totem
  - ttf-ubuntu-font-family
  - ubuntu-software
  - unity-accessibility-profiles
  - unity-webapps-common
  - whoopsie
  - xdg-utils
  - xterm
  - xul-ext-ubufox
  - zeitgeist-core
  - zeitgeist-datahub

- name: upgrade pip
  become: true
  pip: 
    name: pip
    extra_args: --upgrade

- name: add necessary python packages
  become: true
  pip: 
    name: "{{item}}"
  with_items:
    - virtualenv
    - virtualenvwrapper
    # Needed to set the wallpaper (maybe?)
    - psutil

- name: "Run virtualenvwrapper once to create folders"
  shell: "source /usr/local/bin/virtualenvwrapper.sh"
  args:
    creates: "{{ ansible_env.HOME }}/.virtualenvs/initialize"

- name: "Activate the virtualenvwrapper for the user"
  lineinfile: 
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: "source /usr/local/bin/virtualenvwrapper.sh"
    # Do this also non-interactively
    insertbefore: "{{ reference_point_bashrc_string }}"
