- name: Update repositories cache & upgrade packages
  become: true
  apt:
      update_cache: yes
      upgrade: yes
      cache_valid_time: 86400 #One day

- name: Install apt & pip
  become: true
  apt:
      name: "{{item}}"
      state: latest
  with_items:
      - aptitude
      - python-pip
      - python-dev
  notify: apt clean

- name: upgrade pip
  become: true
  pip: 
    name: pip
    extra_args: --upgrade
  notify: clean cache

- name: add packages (pip)
  become: true
  pip: 
    name: "{{item}}"
  with_items:
    - virtualenv
    - virtualenvwrapper

- name: "Run virtualenvwrapper once to create folders"
  shell: "bash /usr/local/bin/virtualenvwrapper.sh"
  args:
    creates: "{{ ansible_env.HOME }}/.virtualenvs/initialize"

# This fixes https://github.com/marvel-nccr/marvel-virtualmachine/issues/21
# Note: this is needed for the 'workon' command and thus needs to go in the .bashrc
- name: "Fix virtualenvwrapper python executable"
  lineinfile: 
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: "export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python"
     
# For safety, also put this into .profile (in case this is needed by non-interactive shells)
- name: "Fix virtualenvwrapper python executable"
  lineinfile: 
    path: "{{ ansible_env.HOME }}/.profile"
    line: "export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python"

# Note: this provides the 'workon' command and thus needs to go in the .bashrc
- name: "Activate the virtualenvwrapper for the user"
  lineinfile: 
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: "source /usr/local/bin/virtualenvwrapper.sh"
