 # On MacOS this requires the passlib python module
- name: Changing password for {{ globalconfig.vm_user }}
  become: True
  user: 
    name: "{{ globalconfig.vm_user }}"
    # string filter is workaround for ansible vault issue
    # https://github.com/ansible/ansible/pull/35406
    password: "{{ globalconfig.vm_password | string | password_hash('sha512') }}"
