 # On MacOS this requires the passlib python module
- name: Changing password for {{ common_vm_user }}
  become: True
  user: 
    name: "{{ common_vm_user }}"
    # string filter is workaround for ansible vault issue
    # https://github.com/ansible/ansible/pull/35406
    password: "{{ common_vm_password | string | password_hash('sha512') }}"
