- name: "Check if swapfile exists"
  stat: path=/swapfile
  register: swapfile_stat

- name: "Create swapfile"
  become: true
  command: "dd if=/dev/zero of=/swapfile bs=1M count=1024"
  when: swapfile_stat.stat.exists == False

- name: "Make the swapfile a valid swap"
  become: true
  command: "mkswap /swapfile"
  when: swapfile_stat.stat.exists == False

- name: "Use the swapfile"
  become: true
  command: "swapon /swapfile"
  when: swapfile_stat.stat.exists == False

- name: "Put a line in fstab to ensure swap is used at boot time"
  become: true
  lineinfile: 
    path: "/etc/fstab"
    line: "/swapfile swap swap defaults 0 0"
  when: swapfile_stat.stat.exists == False
