---
- name: apt clean
  become: True
  listen:
  - apt clean
  apt:
      autoclean: True

- name: remove ~/.cache
  listen: 
  - apt clean
  file:
    state: absent
    path: ~/.cache

- name: apt autoremove
  become: True
  listen:
  - apt clean
  apt:
      autoremove: True

