---
## Note: I'm not sure this whole part is still needed.
- name: copy init.d template
  become: True
  template:
   src: "fix-hostname"
   dest: "/etc/init.d/"
   mode: 0755

- name: enable service forcing hostname to {{ vm_hostname }}
  become: True
  shell: update-rc.d fix-hostname defaults
  args:
    creates: "/etc/rc5.d/S??fix-hostname"

- name: start service to set the hostname
  become: True
  service:
      name: fix-hostname
      state: started

# should will trigger if-up.d script defined in scheduler
- name: restart networking service
  become: True
  service:
      name: networking
      state: restarted

